# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addcomands3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_addcomand(object):
    def setupUi(self, addcomand):
        addcomand.setObjectName("addcomand")
        addcomand.setWindowIcon(QIcon('C:\pythonProject10\pythonProject3\Dabl\photos\icon_window.png'))
        addcomand.resize(425, 281)
        self.label = QtWidgets.QLabel(addcomand)
        self.label.setGeometry(QtCore.QRect(-10, 0, 441, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"C:\pythonProject10\pythonProject3\Dabl\photos\background_1.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addcomand)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(addcomand)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(addcomand)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(addcomand)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(addcomand)
        self.pushButton.setGeometry(QtCore.QRect(30, 220, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #800080; /* Фиолетовый цвет */\n"
"    color: #ffffff; /* Белый цвет текста */\n"
"    border-radius: 10px; /* Радиус закругления углов */\n"
"    border: 2px solid #800080; /* Цвет и толщина границы */\n"
"    padding: 5px 10px; /* Отступы внутри кнопки */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a040a0; /* Фиолетовый цвет при наведении */\n"
"    border: 2px solid #a040a0; /* Цвет границы при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #600060; /* Фиолетовый цвет при нажатии */\n"
"    border: 2px solid #600060; /* Цвет границы при нажатии */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(addcomand)
        self.comboBox.setGeometry(QtCore.QRect(140, 90, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QWidget {\n"
"    background-color: rgb(188, 188, 188); /* Серый цвет фона окна */\n"
"    border-radius: 10px; /* Радиус закругления углов */\n"
"    background-color: #800080; /* Фиолетовый цвет фона для центрального \n"
"}\n"
"\n"
"\n"
"QTextEdit {\n"
"    background-color: #ffffff; /* Белый цвет фона текстового поля */\n"
"    border: 2px solid #a0a0a0; /* Серый цвет границы */\n"
"    border-radius: 8px; /* Радиус закругления углов текстового поля */\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(addcomand)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QWidget {\n"
"    background-color: rgb(188, 188, 188); /* Серый цвет фона окна */\n"
"    border-radius: 10px; /* Радиус закругления углов */\n"
"     \n"
"}\n"
"\n"
"\n"
"QTextEdit {\n"
"    background-color: #ffffff; /* Белый цвет фона текстового поля */\n"
"    border: 2px solid #a0a0a0; /* Серый цвет границы */\n"
"    border-radius: 8px; /* Радиус закругления углов текстового поля */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(addcomand)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 50, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(188, 188, 188); /* Серый цвет фона окна */\n"
"    border-radius: 10px; /* Радиус закругления углов */\n"
"     \n"
"}\n"
"\n"
"\n"
"QTextEdit {\n"
"    background-color: #ffffff; /* Белый цвет фона текстового поля */\n"
"    border: 2px solid #a0a0a0; /* Серый цвет границы */\n"
"    border-radius: 8px; /* Радиус закругления углов текстового поля */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(addcomand)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 170, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QWidget {\n"
"    background-color: rgb(188, 188, 188); /* Серый цвет фона окна */\n"
"    border-radius: 10px; /* Радиус закругления углов */\n"
"     \n"
"}\n"
"\n"
"\n"
"QTextEdit {\n"
"    background-color: #ffffff; /* Белый цвет фона текстового поля */\n"
"    border: 2px solid #a0a0a0; /* Серый цвет границы */\n"
"    border-radius: 8px; /* Радиус закругления углов текстового поля */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(addcomand)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(addcomand)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QWidget {\n"
"    background-color: rgb(188, 188, 188); /* Серый цвет фона окна */\n"
"    border-radius: 10px; /* Радиус закругления углов */\n"
"     \n"
"}\n"
"\n"
"\n"
"QTextEdit {\n"
"    background-color: #ffffff; /* Белый цвет фона текстового поля */\n"
"    border: 2px solid #a0a0a0; /* Серый цвет границы */\n"
"    border-radius: 8px; /* Радиус закругления углов текстового поля */\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(addcomand)
        QtCore.QMetaObject.connectSlotsByName(addcomand)

    def retranslateUi(self, addcomand):
        _translate = QtCore.QCoreApplication.translate
        addcomand.setWindowTitle(_translate("addcomand", "Add command"))
        self.label_2.setText(_translate("addcomand", "name"))
        self.label_3.setText(_translate("addcomand", "trigers"))
        self.label_4.setText(_translate("addcomand", "action"))
        self.label_5.setText(_translate("addcomand", "return"))
        self.pushButton.setText(_translate("addcomand", "add comand"))
        self.comboBox.setItemText(0, _translate("addcomand", "open_link"))
        self.comboBox.setItemText(1, _translate("addcomand", "open_url"))
        self.lineEdit.setPlaceholderText(_translate("addcomand", "alexandr1"))
        self.lineEdit_2.setPlaceholderText(_translate("addcomand", "open youtube"))
        self.lineEdit_3.setPlaceholderText(_translate("addcomand", "yes sir"))
        self.label_6.setText(_translate("addcomand", "parametrs"))
        self.lineEdit_4.setPlaceholderText(_translate("addcomand", "https://github.com/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addcomand = QtWidgets.QWidget()
    ui = Ui_addcomand()
    ui.setupUi(addcomand)
    addcomand.show()
    sys.exit(app.exec_())
