# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dablabla.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowIcon(QIcon('C:\pythonProject10\pythonProject3\Dabl\photos\icon_window.png'))
        Form.resize(794, 623)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, -10, 831, 631))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"C:\pythonProject10\pythonProject3\Dabl\photos\background_1.jpg"))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(170, 130, 441, 341))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #6A1B9A;  /* Темно-ярко фиолетовый цвет кнопки */\n"
"    color: #FFFFFF;  /* Белый цвет текста */\n"
"    border-radius: 10px;  /* Закругленные углы */\n"
"    padding: 10px 20px;  /* Внутренний отступ кнопки */\n"
"    font-family: \'Arial\', sans-serif;  /* Название шрифта (замените на желаемый) */\n"
"    font-size: 16pt;  /* Увеличенный размер шрифта */\n"
"    font-weight: bold;  /* Жирный шрифт */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7B1FA2;  /* Фиолетовый цвет при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A148C;  /* Супер темно-фиолетовый цвет при нажатии */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 520, 181, 51))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #6A1B9A;  /* Темно-ярко фиолетовый цвет кнопки */\n"
"    color: #FFFFFF;  /* Белый цвет текста */\n"
"    border-radius: 10px;  /* Закругленные углы */\n"
"    padding: 10px 20px;  /* Внутренний отступ кнопки */\n"
"    font-family: \'Arial\', sans-serif;  /* Название шрифта (замените на желаемый) */\n"
"    font-size: 16pt;  /* Увеличенный размер шрифта */\n"
"    font-weight: bold;  /* Жирный шрифт */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7B1FA2;  /* Фиолетовый цвет при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4A148C;  /* Супер темно-фиолетовый цвет при нажатии */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 50, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Command window"))
        self.pushButton.setText(_translate("Form", "←"))
        self.pushButton_2.setText(_translate("Form", "Add comand"))
        self.label_2.setText(_translate("Form", "Your commands"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
